https:
 host: 0.0.0.0
 port: "8082"
 
http:
 host: 0.0.0.0
 port: "8081"
 
keystore:
 password: "password"
 
password: "password"

apiid: ""
  
sfdc:
  user: ""
  pass: ""
  token: ""
  
slack:
  consumerkey: ""
  consumersecret: ""

callback:
  app: "https://business-vto-1.us-e2.cloudhub.io"